### ISSUE TITLE
`r-cli==3.0.0` fails to work properly on MacOS.

### ISSUE THREAD

**Issue by matthewwardrop** [conda-forge/r-cli-feedstock#20]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

**Issue:**

Cannot use r-cli via devtools on MacOS in version 3.0.0 (works fine on Linux, and on version 2.5 on mac).

Example:
```
$ Rscript -e "devtools::load_all()"
Error in library.dynam(lib, package, package.lib) : 
  shared object 'cli.dylib' not found
Calls: loadNamespace ... namespaceImportFrom -> asNamespace -> loadNamespace -> library.dynam
Execution halted
```
This works fine with r-cli==2.5.0

**To Reproduce**

Create a new conda environment and install `r-devtools` and `r-cli==3.0.0` and then run `devtools::load_all()` inside a package. I've tested this with a completely fresh environment.

**Comment by matthewwardrop** [comment]
@ocefpaf fyi

**Comment by mfansler** [comment]
I also bumped into this (with `r-cli==3.0.1`), both R 4.0 and 4.1 builds. Slightly more minimal, this simply fails with

**YAML**
```yaml
channels:
  - conda-forge
dependencies:
  - r-cli=3
```

and `Rscript -e "library(cli)"`. What is confusing is that this is what the `meta.yaml` shows it is testing, so I'm not sure why this isn't being caught in the CI.

**Comment by mjsteinbaugh** [comment]
I'm seeing this issue with `r-cli==3.0.1` and `r-cli==3.0.0` on macOS but not `r-cli==2.5.0`, as mentioned above. This is breaking a number of my [bioconda](https://bioconda.github.io/) recipes, to happy to help debug and fix this.

**Comment by mjsteinbaugh** [comment]
@gaborcsardi any advice on how to fix this? The recipe is having issues with `cli.dylib`.

**Comment by mfansler** [comment]
Looking more into the root cause: Package maintainers started including compiled code starting with version 3. Hence, this package is no longer compatible with its previous `noarch` designation and the recipe needs to be updated to include compilers in the build requirements.

@ocefpaf is this something you have time to do, or would you like a PR?

**Comment by ocefpaf** [comment]
> @ocefpaf is this something you have time to do, or would you like a PR?

If you can send a PR it would be awesome. To be honest, I'm not an R expert and I added the package as a favor to others.

**Comment by mjsteinbaugh** [comment]
@mfansler good call, you're right that we need to make a platform-specific build to handle the compiled code. I'll see if I can work on a pull request.

**Comment by mjsteinbaugh** [comment]
Sweet thanks @dbast !
