### ISSUE TITLE
r-cli noarch version on conda-forge

### ISSUE THREAD

**Issue by anutosh491** [conda-forge/r-cli-feedstock#40]
I am curious to know as to why we have 3.0.1 version for noarch and 3.6.3 for the rest 

![Image](https://github.com/user-attachments/assets/24565db6-1fbc-4905-a43c-56e9624063c1)

Is it meant to be that way. My use case here is to use r-cli (noarch from conda-forge) as dependency for compiling R libraries for the `wasm32_unknown_emscripten` target using emscripten.

**Comment by anutosh491** [comment]
Maybe @ocefpaf or @dbast could help me here !

**Comment by mfansler** [comment]
The package switched to being compiled with v3.0.0 (see https://github.com/conda-forge/r-cli-feedstock/issues/20#issuecomment-888607052), but this was not initially caught here, so couple post-v3 builds went through as `noarch`.

Those should be marked as broken if they haven't already.

**Comment by mfansler** [comment]
They are indeed properly marked:

![Image](https://github.com/user-attachments/assets/342a7c24-74c3-4d61-97b4-8ec46033f1a1)

---

So, yes, this is as it should be. I don't really follow the proposed use case - perhaps elaborate. You would have to use `r-cli <3` to get a `noarch` version, but that only covers up through R 4.1.

**Comment by anutosh491** [comment]
Thanks for the reply. 

> I don't really follow the proposed use case - perhaps elaborate. 

Well my use case boils down to fetching a noarch package for r-cli that is compatible with 4.4.1 (which I guess is the latest r-base version there is). Is that not possible ?

**Comment by anutosh491** [comment]
cc @mfansler

**Comment by anutosh491** [comment]
Yes was just confirming for r-cli, I think r-lifecycle was rebuilt with 4.4
